name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Copy takodachi.pyw to takodachi.py (overwrite)
      run: |
        cp -Force takodachi.pyw takodachi.py
    - name: Create Executable
      id: create_executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.11'
        spec: 'takodachi.py'
        upload_exe_with_name: 'takodachi'
        options: --onefile
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./dist/**
