name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy takodachi.pyw to takodachi.py (overwrite)
      run: |
        cp takodachi.pyw takodachi.py
    - name: Create Executable
      id: create_executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.11'
        spec: 'takodachi.py'
        upload_exe_with_name: 'takodachi'
        clean_checkout: 'false'
        requirements: 'requirements.txt'
        options: --onefile --noconsole --add-data "assets/icon_logo.png;assets" --add-data "src/library/logger_exe.conf;src/library"
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./dist/**
