name: Create Release

on:
  push:
    tags:
      - 'V*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Create Executable
      id: create_executable
      uses: sayyid5416@pyinstaller@v1
      with:
        python_ver: '3.11'
        spec: 'takodachi.pyw'
        upload_exe_with_name: 'takodachi'
        options: --onefile
    - name: Release
      uses: softprops/action-gh-release@2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./dist/**
